# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options

analyzer:
  plugins:
    - dart_code_linter

dart_code_linter:
  metrics-exclude:
    - lib/src/generated/**
  rules:
    # TODO: Refactor one after another and enable:
    - prefer-match-file-name: false
    - member-ordering: false
    - prefer-extracting-callbacks: false
    - prefer-single-widget-per-file: false
    - avoid-redundant-async: false
    - avoid-global-state: false
    - avoid-returning-widgets: false
    - avoid-unnecessary-conditionals: false
    - prefer-immediate-return: false
    - avoid-unrelated-type-assertions: false
    - avoid-wrapping-in-padding: false
    - no-equal-then-else: false
    - avoid-dynamic: false
    - prefer-first: false
    - prefer-enums-by-name: false
    - prefer-media-query-direct-access: false
    - prefer-correct-edge-insets-constructor: false
    - avoid-unnecessary-type-assertions: false
